apiVersion: v1
kind: Service
metadata:
  name: pi-hole
  namespace: pihole
spec:
  externalTrafficPolicy: "Cluster"
  loadBalancerIP: 192.168.4.103
  allocateLoadBalancerNodePorts: false
  selector:
    app: pihole
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
    - protocol: TCP
      name: dnstcp
      port: 53
      targetPort: dnstcp
    - protocol: UDP
      name: dnsudp
      port: 53
      targetPort: dnsudp
